### ISSUE TITLE
Index out of bounds in GCNConv layer

### ISSUE THREAD

**Issue by rishabhjoshi** [malllabiisc/ASAP#2]
Hi I tried running your code using the command given and on CPU I get the following error:

```Traceback (most recent call last):
  File "main.py", line 252, in <module>
    val_acc, test_acc   = model.run()
  File "main.py", line 167, in run
    train_loss  = self.run_epoch(train_loader)
  File "main.py", line 67, in run_epoch
    out = self.model(data)
  File "/usr1/home/rjoshi2/envs/torch140/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr1/home/rjoshi2/negotiation_personality/src/negotiation/predict_strategy/ASAP/asap_pool_model.py", line 46, in forward
    x = F.relu(conv(x=x, edge_index=edge_index, edge_weight=edge_weight))
  File "/usr1/home/rjoshi2/envs/torch140/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr1/home/rjoshi2/envs/torch140/lib/python3.7/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 102, in forward
    x.dtype)
  File "/usr1/home/rjoshi2/envs/torch140/lib/python3.7/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 83, in norm
    return edge_index, deg_inv_sqrt[row] * edge_weight * deg_inv_sqrt[col]
IndexError: index 4635 is out of bounds for dimension 0 with size 2631
```

In line 46 of your asap_pool_model file, I saw the shapes of x, edge_index and edge_weight. I even saw the max value of edge_index : 
```
((Pdb) x.shape
torch.Size([2631, 64])
(Pdb) edge_index.shape
torch.Size([2, 58576])
(Pdb) edge_weight.shape
torch.Size([58576])
(Pdb) torch.max(edge_index)
tensor(5206)
(Pdb) x = F.relu(conv(x=x, edge_index=edge_index, edge_weight=edge_weight))
*** IndexError: index 4635 is out of bounds for dimension 0 with size 2631
```
Could you help me debug this?

**Comment by rishabhjoshi** [comment]
Hi
I figured out the issue.
I was using Pytorch version 1.4.0, latest pytorch-geometric / sparse / cluster etc. 
After converting to Pytorch 1.1.0 and the versions mentioned in the requirements, i had to additionally use version **1.4.3 of Pytorch-Geometric** (which was not mentioned in the requirements) to get it to finally work.

**Comment by ekagra-ranjan** [comment]
Hi @rishabhjoshi ,

Thank you for letting us know the issue and a potential fix. 
During the course of this project, we were using PyTorch (1.0) and PyG (1.2.1)  which was latest at that time. The issue might be due to the incompatibility of some function across different version of the dependent libraries. The code runs fine without any changes needed with the **latest** versions: Pytorch (1.5), **PyG (1.4.3)**, scatter (2.0.4) and sparse (0.6.3). Thanks to your suggestion, we have rectified our Readme to better reflect this and avoid any confusion :)
