### ISSUE TITLE
got an unexpected keyword argument 'edge_weight'

### ISSUE THREAD

**Issue by chexiangying** [malllabiisc/ASAP#4]

**Comment by chexiangying** [comment]
warnings.warn(out)
Traceback (most recent call last):
  File "main.py", line 255, in <module>
    val_acc, test_acc	= model.run()
  File "main.py", line 170, in run
    train_loss	= self.run_epoch(train_loader)
  File "main.py", line 70, in run_epoch
    out	= self.model(data)
  File "/home/mwx/.conda/envs/torch_tmp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mwx/cxy/ASAP/asap_pool_model.py", line 42, in forward
    x, edge_index, edge_weight, batch, perm = self.pool1(x=x, edge_index=edge_index, edge_weight=None, batch=batch)
  File "/home/mwx/.conda/envs/torch_tmp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mwx/cxy/ASAP/asap_pool.py", line 112, in forward
    fill_value=fill_value, num_nodes=num_nodes.sum())
TypeError: add_remaining_self_loops() got an unexpected keyword argument 'edge_weight'

**Comment by Yuruzu** [comment]
I got the same error, have you solved it?

**Comment by ot4f** [comment]
change "edge_weight" to "edge_attr "
